{
 "title": "Mysticeti",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(latency_s_count[1m])" }
   ]
  },
  {
   "title": "Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(transaction_certified_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Certificate p50"
    },
    {
     "expr": "avg(transaction_certified_latency{v=\"p90\"}) / 1000",
     "legendFormat": "Certificate p90"
    },
    {
     "expr": "avg(transaction_committed_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Tx Commit p50"
    },
    {
     "expr": "avg(transaction_committed_latency{v=\"p90\"}) / 1000",
     "legendFormat": "Tx Commit p90"
    },
    {
     "expr": "avg(certificate_committed_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Cert commit p50"
    },
    {
     "expr": "avg(certificate_committed_latency{v=\"p90\"}) / 1000",
     "legendFormat": "Cert commit p90"
    }
   ]
  },
  {
   "title": "Committed Leaders (view of Node 0)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "committed_leaders_total", "legendFormat": "Node {{authority}}" }
   ]
  },
  {
   "title": "Network receive (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\"}[1m]) / 1024 / 1024 * 8"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 /1024"
    }
   ]
  },
  {
   "title": "Proposed block size p50(Kbytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "proposed_block_size_bytes{v=\"p50\"} / 1024"
    }
   ]
  },
  {
   "title": "Core lock utilization (fraction)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(core_lock_util[1m]) / 1000000"
    }
   ]
  },
  {
   "title": "Core lock wait (fraction)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(core_lock_wait[1m]) / 1000000"
    }
   ]
  }
 ]
}